### PR TITLE
don't call recaptcha if there's no site_key

### PR DESCRIPTION
**Pull request by Zerowalker**

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Please note that you are contributing to a soon-to-be deprecated version. Please do use the newer version of Municipop solution @ https://github.com/municipio-se/municipio-deployment . 

Version 3.0 of Municipio is updated with a brand new frontend, including customizer support. This version have many improvements regarding GDPR/Schrems which i belive that you are fixing here.  

I'm happy to merge this update, if you add some {}.

**Comment by Zerowalker** [comment]
Does version 3.0 have it's own "Customer-feedback" you mean?
When is 3.0 expected to be released?

**Comment by sebastianthulin** [comment]
> Does version 3.0 have it's own "Customer-feedback" you mean? When is 3.0 expected to be released?

Yes. It has a new frontend-functionality. The backend functionality is almost the same. The new version of customer feedback can be found @ 3.0/develop branch. 

Version 3.0 is ready to be used in production. We have however not come around to making it official by mergint o master branches. 

You can find a full deployment instruction of 3.0 here: https://github.com/municipio-se/municipio-deployment 

Have a look in the composer.json files to find out about the latest branches of each repository. 

3.0 is not compatible with most of our old plugins, these must have a corresponding 3.0 branch. 

Example sites using 3.0 today are (currently 168 sites): 
https://kulturkortet.se/
https://dunkerskulturhus.se/ 
https://helsingborg.se/
https://www.horby.se/
https://familjenhelsingborg22.se/

**Comment by Zerowalker** [comment]
ah didn't know it was ready for production.
I suggest to make that clear as I believe others would look at 3.0/develop as "developing towards 3.0" and not ready for production.

will checkout the 'municipio-deployment', thanks:)!

**Pull request merged**
